name: Swift
on:
  push:
    branches: [ feature/jaewook/test-code ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: tuist/tuist-action@0.13.0
      with:
         command: 'generate'
         arguments: '--project-only'
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode.app
    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash
    - name: Build
      run: |
           xcodebuild clean build -workspace "Tooda.xcworkspace" -scheme "ToodaTest" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
    - name: Run tests
      run: | 
        xcodebuild test -project Tooda.xcworkspace -scheme ToodaTests -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
