name: Swift
on:
  push:
    branches: [ feature/jaewook/test-code ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: tuist/tuist-action@0.13.0
      with:
         command: 'generate'
         arguments: '--project-only'
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash
    - name: Build
      run: swift build -v
    - name: Run tests
      run: | 
        xcodebuild test -project Tooda.xcodeproj -scheme Tooda -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
